//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int IDimage { get; set; }
        public string ImageLink { get; set; }
        public int IdHotel { get; set; }
    
        public virtual HOTEL HOTEL { get; set; }
    }
}
