//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int IdReview { get; set; }
        public string TitleReview { get; set; }
        public string DescReview { get; set; }
        public int IdHotel { get; set; }
        public int IdUser { get; set; }
    
        public virtual HOTEL HOTEL { get; set; }
        public virtual User User { get; set; }
    }
}
